#!/bin/bash
if [ $# -lt 1 ]; then
  echo "Need a dump file"
  exit 1
fi

docker-compose up -d
./upload "$1"

# reexport
output=$( echo "$1" | sed 's/\.sql/-clean.sql/' )
docker-compose exec -T database mysqldump -uroot -proot --skip-opt dump > $output
