#!/bin/bash
if [ $# -lt 1 ]; then
  echo "Need a dump file"
  exit 1
fi

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/common.sh"

dump="$1"

run_db_container
wait_for_port $MYSQL_PORT

# upload the dump
docker exec -i dump_db mysql -h localhost -uroot -p$ROOT_PWD dump < $dump

# reexport
output=$( echo $dump | sed 's/\.sql/-clean.sql/' )
docker exec -i dump_db mysqldump -h localhost -uroot -p$ROOT_PWD --skip-opt dump > $output
