#!/bin/bash
if [ $# -lt 1 ]; then
  echo "Need a dump file"
  exit 1
fi

docker-compose up -d

./wait_for_port 9906
./upload "$1"
./wait_for_port 9980

open "http://localhost:9980/db_structure.php?server=1&db=dump"